version: '3.3'

volumes:
  db_data:
  static:
  media:

services:
  db:
    container_name: pingbin74-db
    image: postgres:15.1
    env_file:
      - .env
    volumes: 
      - db_data:/var/lib/postgresql/data
    restart: always
  
  backend:
    container_name: pingbin74-backend
    build: ../backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/var/html/media
    restart: always

  frontend:
    container_name: pingbin74-front
    build: ../frontend
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

