# Generated by Django 4.2.21 on 2025-05-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
        ("recipes", "0005_rename_description_recipe_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredient",
                to="ingredient.ingredient",
                verbose_name="Ингредиенты",
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredient.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
